import type { Metadata } from "next";
import "./globals.css";
import { Archivo } from "next/font/google";
import { Toaster } from "sonner";
import AppProvider from "@/shared/app-provider";

const font = Archivo({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <AppProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          {children}
          <Toaster richColors position="bottom-center" />
        </AppProvider>
      </body>
    </html>
  );
}
